<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>HorseWhistle</AssemblyName>
    <RootNamespace>HorseWhistle</RootNamespace>
    <Version>1.3.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableHarmony>false</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.*" />
  </ItemGroup>

</Project>
